version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: AIELTS_database
    ports:
      - "2204:27017"
    volumes:
      - mongodb-data:/AIELTS/database
    restart: unless-stopped
volumes:
  mongodb-data:
