version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: AIELTS_database
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/AIELTS/database
volumes:
  mongodb-data: