version: '1'

services:
  mongodb:
    image: mongo:latest
    container_name: AIELTS_database
    ports:
      - "2204:27017"
    volumes:
      - mongodb-data:/AIELTS/database
    restart: unless-stopped

  server:
    build:
      context: server
    ports:
      - "5050:5050"
    restart: unless-stopped
    depends_on:
      - mongodb
  
volumes:
  mongodb-data: