version: '3.2'
services:
  whisper.cpp:
    container_name: llm-grader
    image: llm-grader
    build: .
    ports:
      - "14023:14023"
    volumes:
      - ./uploads:/code/uploads
    restart: always
volumes:
  uploads: